### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by CyricPL** [pelwer1/Deal-Init#3]
First, thank you for this! Unfortunately right now I'm not able utilize the script - when I enable it, I get SyntaxError: Unexpected identifier. Not sure how I can go about resolving this?

**Comment by pelwer1** [comment]
I see this type of problem when the TurnOrder is not "flushed" between
sessions or pages.

Flush = Open Turn Order > Poke Blue Gear Button > Poke Red "Remove all
Turns" button

My workflow, when I use the script is like this:

   - New Roll20 session  or New Page or New Encounter on Same Page - *Flush
   turn order*
   - New Encounter: *!deal-init --reset*
   - New Round: *!deal-init*
   - Someone Spends a Benny to Draw a New Card: *!deal-init --deal2chat*
   (then I just manually move them around in the TurnOrder)


Flush the TurnOrder and try it again.  Let me know if you still have
problems

Thanks,
Pat.

A little nonsense, now and then, is relished by the wisest men.  - Willy
Wonka

**Comment by CyricPL** [comment]
OK, so error is resolved and as is so often the case, the issue was with the end user. I was actually getting the syntax error message trying to spin up the API sandbox in the first place, but I still gave your suggestion a try anyway. No dice. Then I go back to disable it again and realize that I had inadvertently pasted in a bunch of text from the GitHub page below your actual code. Facepalm. Thanks again!

**Comment by pelwer1** [comment]
great news!






Thanks,
Pat.

A little nonsense, now and then, is relished by the wisest men.  - Willy
Wonka
