### ISSUE TITLE
Sorting not working correctly

### ISSUE THREAD

**Issue by fattom23** [pelwer1/Deal-Init#4]
I'm noticing that the sort function doesn't seem to be working correctly anymore. For example, my last sort came back BJo, 10H, 9C, JD, JH, QH. I apologize, I don't know enough about the code to be able to figure out what's happening. Are there any suggestions on how to fix this?

**Comment by pelwer1** [comment]
Deal Init, sorts the cards before inserting them into the turn order.  You cannot use Roll20's turn tracker tools to sort initiative after running deal init. If you need to manipulate the order after running dealinit for the round, just drag the cards into the order you want.

The reason for this is that I am not inserting cards into the turn order - Roll20 doesn't support that in the API.  It's just text strings.  So when you tell Roll20 to sort by suit, it doesn't find cards and uses some other rule for sorting the text i put in the turn order.

If this doesn't address your problem. Please send me the exact steps you go through to create the error.

**Comment by fattom23** [comment]
I figured out the problem. I forgot that I had running the VTT Enhancement Suite, which attempts to automatically sort the Initiative Tracker. Once I disabled that, everything worked out fine. Thanks a million for the fast turnaround.
